version: '3.0'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./data:/var/lib/mysql"
      - "./mysql-init:/docker-entrypoint-initdb.d"
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root12345 
      - MYSQL_DATABASE=app 
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=user12345
